name = "Normalize"
uuid = "57040077-074e-4771-b556-e8e2740270f5"
authors = ["Kwat Medetgul-Ernar <kwat.me@icloud.com>"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Statistics = "1.5"
StatsBase = "0.33"
julia = "1.6"
